### ISSUE TITLE
Google Fusion Table is not available

### ISSUE THREAD

**Issue by ululele** [3dcitydb/tutorials#2]
Hi!
I am following the Tutorial 4.0 and I can not use Google Fusion Table. It is not available anymore. 
Do you have an alternative and could you explain me how to use it regarding to 3dcitydb?

Thanks.

**Comment by Son-HNguyen** [comment]
Hi,

the Google Fusion Tables Service was no longer active since September 2019. Alternatively, you can use Google Spreadsheets or PostgreSQL/PostgREST to display the thematic information in the 3DCityDB Web Map Client. The Web Map Client starting from version 1.8.1 is capable of handling both of the services. Please refer to the [release notes](https://github.com/3dcitydb/3dcitydb-web-map/releases/tag/v1.8.1) for more details.

If you have any questions, feel free to ask.

Best,
Son

**Comment by ululele** [comment]
Thanks so much for your help. I used Google Spreadsheets and it worked :)

**Comment by Son-HNguyen** [comment]
Glad it helped! ;-)
